# Generated by Django 3.2.7 on 2022-03-26 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_adoption_requests', to='core.person'),
        ),
    ]
