# Generated by Django 3.2.7 on 2022-06-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220326_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='type',
            new_name='animal_type',
        ),
    ]
