# Generated by Django 3.2.7 on 2022-06-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_type_animal_animal_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionrequest',
            options={'verbose_name': 'Adoption request', 'verbose_name_plural': 'Adoption requests'},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.AlterModelOptions(
            name='animalphoto',
            options={'verbose_name': 'Animal photo', 'verbose_name_plural': 'Animal photos'},
        ),
        migrations.AlterModelOptions(
            name='animaltype',
            options={'verbose_name': 'Animal type', 'verbose_name_plural': 'Animals type'},
        ),
        migrations.AlterModelOptions(
            name='blockedreason',
            options={'verbose_name': 'Block reason', 'verbose_name_plural': 'Block reasons'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='vaccinebook',
            options={'verbose_name': 'Vaccine book', 'verbose_name_plural': 'Vaccines book'},
        ),
    ]
